services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: alphabeta
      POSTGRES_PASSWORD: "alphabeta_prod_12345"
      POSTGRES_DB: alphabeta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alphabeta -d alphabeta"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env.docker
    environment:
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      DATABASE_URL: postgresql://alphabeta:alphabeta_prod_12345@db:5432/alphabeta?schema=public
      JWT_SECRET: your_secret_dev_key_for_alphabeta_store
      JWT_ACCESS_SECRET: your_secret_access_key_for_alphabeta_dev_123
      JWT_REFRESH_SECRET: your_secret_refresh_key_for_alphabeta_dev_123
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      ADMIN_NAME: Admin
      ADMIN_EMAIL: admin@alphabeta.com
      ADMIN_PASSWORD: Admin@123456
      API_PREFIX: api/v1
      PORT: 3001
      REDIS_URL: redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:3000/api/v1
        INTERNAL_API_BASE_URL: http://backend:3001/api/v1
    restart: unless-stopped
    env_file:
      - ./frontend/.env.docker
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3000/api/v1
      INTERNAL_API_BASE_URL: http://backend:3001/api/v1
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
